name: Continuos Integration

on:
  push:

jobs:
  tests:
    name: Tests
    tuns-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Composer install
        run: ./run composer install

      - name: PHPUnit
        run: ./run test